services:
  mailer:
    container_name: setup-laravel_mailer
    image: axllent/mailpit
    ports:
      - "8025"
      - "32770:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - setup-laravel_network
  php:
    container_name: setup-laravel_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./laravel:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-laravel_network

  nginx:
    container_name: setup-laravel_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-laravel_network

  postgres:
    container_name: setup-laravel_postgres
    image: postgres:15
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - setup-laravel_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_laravel
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123456

  redis:
    container_name: setup-laravel_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispassword
    volumes:
      - redis_data:/data
    networks:
      - setup-laravel_network

networks:
  setup-laravel_network:
    driver: bridge

volumes:
  setup-data:
    driver: local
  redis_data:
    driver: local
